/**
 * Standard Platform Error Codes
 */
export enum ErrorCode {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',

  // Users & Profiles
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INACTIVE = 'USER_INACTIVE',
  CREATOR_PROFILE_NOT_FOUND = 'CREATOR_PROFILE_NOT_FOUND',
  BUSINESS_PROFILE_NOT_FOUND = 'BUSINESS_PROFILE_NOT_FOUND',

  // KYC & Verification
  KYC_NOT_VERIFIED = 'KYC_NOT_VERIFIED',
  KYC_ALREADY_SUBMITTED = 'KYC_ALREADY_SUBMITTED',
  KYC_INVALID_DOCUMENTS = 'KYC_INVALID_DOCUMENTS',
  KYC_REJECTED = 'KYC_REJECTED',

  // Campaigns
  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_NOT_ACTIVE = 'CAMPAIGN_NOT_ACTIVE',
  CAMPAIGN_ALREADY_CLOSED = 'CAMPAIGN_ALREADY_CLOSED',
  CAMPAIGN_BUDGET_MISMATCH = 'CAMPAIGN_BUDGET_MISMATCH',
  CAMPAIGN_DEADLINE_PASSED = 'CAMPAIGN_DEADLINE_PASSED',
  CAMPAIGN_CREATOR_LIMIT_REACHED = 'CAMPAIGN_CREATOR_LIMIT_REACHED',

  // Bids & Negotiations
  BID_NOT_FOUND = 'BID_NOT_FOUND',
  BID_ALREADY_EXISTS = 'BID_ALREADY_EXISTS',
  BID_ALREADY_ACCEPTED = 'BID_ALREADY_ACCEPTED',
  BID_ALREADY_REJECTED = 'BID_ALREADY_REJECTED',
  BID_INVALID_AMOUNT = 'BID_INVALID_AMOUNT',
  BID_CANNOT_COUNTER = 'BID_CANNOT_COUNTER',

  // Collaborations & State Machine
  COLLABORATION_NOT_FOUND = 'COLLABORATION_NOT_FOUND',
  COLLABORATION_INVALID_STATE_TRANSITION = 'COLLABORATION_INVALID_STATE_TRANSITION',
  COLLABORATION_MAX_REVISIONS_EXCEEDED = 'COLLABORATION_MAX_REVISIONS_EXCEEDED',
  COLLABORATION_ALREADY_COMPLETED = 'COLLABORATION_ALREADY_COMPLETED',
  COLLABORATION_ALREADY_CANCELLED = 'COLLABORATION_ALREADY_CANCELLED',
  COLLABORATION_DELIVERABLE_REQUIRED = 'COLLABORATION_DELIVERABLE_REQUIRED',

  // Payments & Escrow
  PAYMENT_ESCROW_NOT_FUNDED = 'PAYMENT_ESCROW_NOT_FUNDED',
  PAYMENT_ALREADY_HELD = 'PAYMENT_ALREADY_HELD',
  PAYMENT_ALREADY_RELEASED = 'PAYMENT_ALREADY_RELEASED',
  PAYMENT_ALREADY_REFUNDED = 'PAYMENT_ALREADY_REFUNDED',
  PAYMENT_VERIFICATION_FAILED = 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_ORDER_CREATION_FAILED = 'PAYMENT_ORDER_CREATION_FAILED',
  PAYMENT_REFUND_FAILED = 'PAYMENT_REFUND_FAILED',
  PAYMENT_INVALID_AMOUNT = 'PAYMENT_INVALID_AMOUNT',

  // Disputes
  DISPUTE_NOT_FOUND = 'DISPUTE_NOT_FOUND',
  DISPUTE_ALREADY_EXISTS = 'DISPUTE_ALREADY_EXISTS',
  DISPUTE_ALREADY_RESOLVED = 'DISPUTE_ALREADY_RESOLVED',
  DISPUTE_INVALID_SPLIT = 'DISPUTE_INVALID_SPLIT',

  // Reviews
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_SUBMITTED = 'REVIEW_ALREADY_SUBMITTED',
  REVIEW_COLLABORATION_NOT_COMPLETED = 'REVIEW_COLLABORATION_NOT_COMPLETED',

  // Chat & Moderation
  CHAT_THREAD_NOT_FOUND = 'CHAT_THREAD_NOT_FOUND',
  CHAT_OFF_PLATFORM_CONTACT_DETECTED = 'CHAT_OFF_PLATFORM_CONTACT_DETECTED',
  CHAT_THREAD_CLOSED = 'CHAT_THREAD_CLOSED',

  // General & Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
