/**
 * Core platform enums used across backend, admin, and mobile applications.
 */

export enum UserRole {
  ADMIN = 'ADMIN',
  CREATOR = 'CREATOR',
  BUSINESS = 'BUSINESS',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum VerificationStatus {
  UNSUBMITTED = 'UNSUBMITTED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  REQUIRES_INFO = 'REQUIRES_INFO',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  IN_REVIEW = 'IN_REVIEW',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CLOSED = 'CLOSED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum BidStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  WITHDRAWN = 'WITHDRAWN',
  COUNTERED = 'COUNTERED',
}

export enum CollaborationStatus {
  APPLIED = 'APPLIED',
  PENDING = 'PENDING',
  NEGOTIATING = 'NEGOTIATING',
  OFFERED = 'OFFERED',
  ACCEPTED = 'ACCEPTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  DELIVERABLE_SUBMITTED = 'DELIVERABLE_SUBMITTED',
  SUBMITTED = 'SUBMITTED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  APPROVED = 'APPROVED',
  PENDING_PAYOUT = 'PENDING_PAYOUT',
  PAID = 'PAID',
  PAID_OUT = 'PAID_OUT',
  COMPLETED = 'COMPLETED',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
  DECLINED = 'DECLINED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  HELD = 'HELD',
  ESCROW_HELD = 'ESCROW_HELD',
  LOCKED = 'LOCKED',
  RELEASED = 'RELEASED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  DISPUTED = 'DISPUTED',
  FAILED = 'FAILED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  RESOLVED_BUSINESS = 'RESOLVED_BUSINESS',
  RESOLVED_CREATOR = 'RESOLVED_CREATOR',
  RESOLVED_PARTIAL = 'RESOLVED_PARTIAL',
  RESOLVED_SPLIT = 'RESOLVED_SPLIT',
  ESCALATED = 'ESCALATED',
}

export enum DisputeOutcome {
  REFUND_BUSINESS = 'REFUND_BUSINESS',
  PAYOUT_CREATOR = 'PAYOUT_CREATOR',
  PARTIAL_BOTH = 'PARTIAL_BOTH',
  NO_ACTION = 'NO_ACTION',
}

export enum ReviewType {
  BUSINESS_TO_CREATOR = 'BUSINESS_TO_CREATOR',
  CREATOR_TO_BUSINESS = 'CREATOR_TO_BUSINESS',
}

export enum DeliverableType {
  INSTAGRAM_REEL = 'INSTAGRAM_REEL',
  INSTAGRAM_STORY = 'INSTAGRAM_STORY',
  YOUTUBE_VIDEO = 'YOUTUBE_VIDEO',
  YOUTUBE_SHORT = 'YOUTUBE_SHORT',
  SOCIAL_POST = 'SOCIAL_POST',
  EVENT_APPEARANCE = 'EVENT_APPEARANCE',
  OTHER = 'OTHER',
}

export enum ChatReportReason {
  SPAM = 'SPAM',
  HARASSMENT = 'HARASSMENT',
  OFF_PLATFORM_CONTACT = 'OFF_PLATFORM_CONTACT',
  INAPPROPRIATE = 'INAPPROPRIATE',
  OTHER = 'OTHER',
}

export enum NotificationChannel {
  PUSH = 'PUSH',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  IN_APP = 'IN_APP',
}

export enum NotificationType {
  BID_RECEIVED = 'BID_RECEIVED',
  BID_ACCEPTED = 'BID_ACCEPTED',
  BID_REJECTED = 'BID_REJECTED',
  BID_COUNTERED = 'BID_COUNTERED',
  PAYMENT_HELD = 'PAYMENT_HELD',
  PAYMENT_RELEASED = 'PAYMENT_RELEASED',
  DELIVERABLE_SUBMITTED = 'DELIVERABLE_SUBMITTED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  COLLABORATION_APPROVED = 'COLLABORATION_APPROVED',
  DISPUTE_RAISED = 'DISPUTE_RAISED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  NEW_MESSAGE = 'NEW_MESSAGE',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  KYC_REQUIRES_INFO = 'KYC_REQUIRES_INFO',
  CAMPAIGN_EXPIRING = 'CAMPAIGN_EXPIRING',
}

export enum SocialPlatform {
  INSTAGRAM = 'INSTAGRAM',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
}

export enum KycDocumentType {
  PAN = 'PAN',
  GST = 'GST',
  AADHAAR = 'AADHAAR',
  PASSPORT = 'PASSPORT',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
}

export enum EscrowTransactionType {
  FUND = 'FUND',
  RELEASE = 'RELEASE',
  REFUND = 'REFUND',
  SPLIT_REFUND = 'SPLIT_REFUND',
  FEE_DEDUCTION = 'FEE_DEDUCTION',
}
